### ISSUE TITLE
i18n on context menu "delete" and "clone"

### ISSUE THREAD

**Issue by conlaoch1** [retejs/context-menu-plugin#12]
Hi! Is there a possibility to translate the context menu that appears when right-clicking a node, namely "delete" and "clone?". The function "rename" does not cover those entries.
Thanks!

**Comment by Ni55aN** [comment]
Hi! Try something like that:

```js
allocate(component) {
    return component.path.map(i18n);
},
rename(component) {
    return i18n(component.name);
},
```

http://i18njs.com/

**Comment by conlaoch1** [comment]
Hi! Thanks for the quick reply. Unfortunately, the context menu for "delete" and "clone" is not iterated in those functions, only the node components themselves. Are those handled differently?
Thanks!

**Comment by Ni55aN** [comment]
You can to extend the `Item` component

```js
editor.use(ContextMenuPlugin, {
    vueComponent: {
        extends: { ...ContextMenuPlugin.Menu },
        components: {
            Item: {
                name: 'Item',
                template: `<div class="item"
                    @click="onClick($event)"
                    @mouseover="showSubitems()"
                    @mouseleave="timeoutHide()"
                    :class="{ hasSubitems }"
                    > {{v18n(item.title)}}
                    <div class="subitems" v-show="hasSubitems && this.visibleSubitems">
                        <Item v-for="subitem in item.subitems"
                        :key="subitem.title"
                        :item="subitem"
                        :args="args"
                        :delay="delay"
                        ></Item>
                    </div>
                </div>`,
                methods: { v18n(v) { return `[translate ${v}]`; }},
                extends: { ...ContextMenuPlugin.Item, _scopeId: null,  render: null }
            }
        }
    }
});
```

Although Single-file component will be more preferred

**Comment by VitaliyDemchuk** [comment]
> You can to extend the `Item` component
> 
> ```js
> editor.use(ContextMenuPlugin, {
>     vueComponent: {
>         extends: { ...ContextMenuPlugin.Menu },
>         components: {
>             Item: {
>                 name: 'Item',
>                 template: `<div class="item"
>                     @click="onClick($event)"
>                     @mouseover="showSubitems()"
>                     @mouseleave="timeoutHide()"
>                     :class="{ hasSubitems }"
>                     > {{v18n(item.title)}}
>                     <div class="subitems" v-show="hasSubitems && this.visibleSubitems">
>                         <Item v-for="subitem in item.subitems"
>                         :key="subitem.title"
>                         :item="subitem"
>                         :args="args"
>                         :delay="delay"
>                         ></Item>
>                     </div>
>                 </div>`,
>                 methods: { v18n(v) { return `[translate ${v}]`; }},
>                 extends: { ...ContextMenuPlugin.Item, _scopeId: null,  render: null }
>             }
>         }
>     }
> });
> ```
> 
> Although Single-file component will be more preferred

i have warning and context menu not show: `[Vue warn]: Failed to mount component: template or render function not defined.`
