### ISSUE TITLE
Custom context menu on nodes

### ISSUE THREAD

**Issue by flobiber** [retejs/context-menu-plugin#13]
If i do a right-click on node i got the following options: Delete & Clone.

Is there a possibility to add some custom entry to this?

**Comment by flobiber** [comment]
Can i disable this menu?

**Comment by Ni55aN** [comment]
No

**Comment by flobiber** [comment]
i have implement that kind of feature.
Is it possible to create a pull-request?

**Comment by Ni55aN** [comment]
Yes, sure. If you have not started doing it, I can do it now. This should not take a lot of time.

**Comment by flobiber** [comment]
I had finished it, but i havn't enough rights to push to your repo.

**Comment by Ni55aN** [comment]
You should to make Pull request

**Comment by Ni55aN** [comment]
I have published v0.4.0 manually (Microsoft broke something and paused Webhook on GitHub, so travis does not react to the commit)

**Comment by jadhavsuraj2207** [comment]
Hi, 
I want to hide the context menu of 'delete' and 'clone' for specific component ? how can i do this? 


 I want to hide the context menu when I right click on the start call.Is there anyway to do it ? 
Thanks

**Comment by eyasman** [comment]
Is there a possibility to customize right-click node menu?
