### ISSUE TITLE
Disable context menu of 'delete' and 'clone' 

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/context-menu-plugin#17]
I want to hide the context menu of 'delete' and 'clone' for specific component ? how can i do this? 

 I want to hide the context menu when I right click on the start call.Is there anyway to do it ? 
Currently using the updated version (0.4.0)
Thanks

_Originally posted by @jadhavsuraj2207 in https://github.com/retejs/context-menu-plugin/issues/13#issuecomment-507978128_

**Comment by Ni55aN** [comment]
In v0.4.1 I have added a new event to solve this problem.

Prevent showing context menu
```js
editor.on('showcontextmenu', ({ e, node }) => { // e - MouseEvent, node - Node instance or null
    return Boolean(node); // show context menu for nodes only
});
```
Prevent context menu for particular Node
```js
class AddComponent extends Rete.Component {
    constructor(){
        // ...
        this.data.noContextMenu = true;
    }
// ...

editor.on('showcontextmenu', ({ node }) => {
    return !node || !editor.components.get(node.name).data.noContextMenu;
});
```

**Comment by jadhavsuraj2207** [comment]
Thanks for quick reply @Ni55aN . I'll definately try it out.

**Comment by jadhavsuraj2207** [comment]
Hi, thanks for the help. It works like a charm !!

**Comment by nikola-bozin-org** [comment]
Is there by any chance that showcontextmenu event can be updated in this version too: https://github.com/rajasegar/rete-context-menu-plugin-react ? Because when I tried using it in browser I got error: 
```
Ucaught (in promise) Error: The event showcontextmenu does not exist
 ```

**Comment by Ni55aN** [comment]
@nikola-bozin-org probably, you added the event listener before connecting the plugin

**Comment by nikola-bozin-org** [comment]
> @nikola-bozin-org probably, you added the event listener before connecting the plugin

Maybe?
Im using version: 
```
0.0.8
```
But I can confirm I did this:
``` 
import ContextMenuPlugin, {ReactMenu} from 'rete-context-menu-plugin-react';

```
  ```
  editor.use(ContextMenuPlugin,{
    Menu:ReactMenu
  });
  
  ```
  and than before
  ```
   editor.on('process...)
  ```
  I have put:
   ```
    editor.on('showcontextmenu', ({ e, node }) => {
    console.info('Showing CTX Menu')
    return Boolean(node);
  });
  ```
  
  am I missing something?

**Comment by Ni55aN** [comment]
`rete-context-menu-plugin-react` is not an official plugin, so I can't comment on how it works.

You might consider switching to v2 of the framework, as it resolves the issue with different renders for the context menu, although it is still in beta.

**Comment by nikola-bozin-org** [comment]
Thanks for your information.
Is there a documentation on how to transition from V1 to V2?

Also, I see that Rete is natively built for Vue. Is it still possible to use it fully in React?

**Comment by Ni55aN** [comment]
https://retejs.org/docs/migration

> I see that Rete is natively built for Vue

no, it's not. The v1 supports all three render plugins. It's just that the context menu it's based on Vue

**Comment by nikola-bozin-org** [comment]
Thank you!
