### ISSUE TITLE
Context menu overlapping on nodes when clicking on nodes

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/context-menu-plugin#21]
Hi,
when I right click on node , the context menu open above node.
I want the context-menu to display near to the respective node even if I right click on the node. so that my node will be fully visible and besides that context menu will be positioned. 

As u can see in above image, context menu is overlapping node .
In index.js file on context menu function , menu.show(x,y,{node}) is used which clientX,clientY value .

is there any way to position it beside node ?

**Comment by Ni55aN** [comment]
Try to mutate the properties, but this is a rather unreliable way.

```js
editor.on('showcontextmenu', ({ e }) => {
  e.clientX = // 
  e.clientY = // 
});
```

**Comment by jadhavsuraj2207** [comment]
Hi,
Thanks for a reply .
I tried to put the values of e.clientX and e.clientY with reference to the node position in the editor.
i.e.  e.clientX = node.position[0] & e.clientY =  node.position[1]. but position is not giving me the correct values besides the node . what should be the values of e.clientX & e.clientY ?
Also , can we show the context menu when I hover on the node ?
Thanks .
