### ISSUE TITLE
context menu on connection

### ISSUE THREAD

**Issue by MariuszMularczyk** [retejs/context-menu-plugin#24]
Hey, is there a possibility to get a context menu by clicking on the connection line or set a label on connection?

**Comment by Ni55aN** [comment]
At the moment you can listen `contextmenu` event on connection and open your own context menu (current version of this plugin doesn't support additional menu)

```js
editor.on('renderconnection', ({ el }) => {
  el.addEventListener('contextmenu', (e) => {
    e.stopPropagation();
    e.preventDefault();
    // open your context menu
  });
});
```

**Comment by Ni55aN** [comment]
I'll add support for an additional menu in the next version

**Comment by MariuszMularczyk** [comment]
Thanks!
