### ISSUE TITLE
vue prop mutated within child component

### ISSUE THREAD

**Issue by cvisl** [retejs/context-menu-plugin#27]
Within src/menu/Search.vue something changes the prop value because of the v-model and its also send with the emit event and doubly added to filter in the parent in src/menu/Menu.vue. Maybe make the value data instead of prop if you send it through the emit?

**Comment by darrenmothersele** [comment]
> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

```
found in

---> <Search> at /home/travis/build/retejs/context-menu-plugin/src/menu/Search.vue
       <Menu> at /home/travis/build/retejs/context-menu-plugin/src/menu/Menu.vue
         <Root>
```

**Comment by Hatead1** [comment]
I see this warn, too

**Comment by darrenmothersele** [comment]
I decided to remove the Rete context menu plugin from my project and use Vue Context instead: https://www.npmjs.com/package/vue-context
I found this easier to customise.

**Comment by Hatead1** [comment]
I have two same projects on different computers, versions are the same, on one computer everything is normal, on the second - "Avoid mutating a prop directly". And it does not depend on the c-m-p code.

**Comment by Hatead1** [comment]
my version of Search.vue (work without warn)

```
<template><div class="search"><input v-model="valuelocal"/></div></template>

<script>
export default {
  props: ['value', 'search'],
  data() { return { valuelocal: this.value } },
  watch: { valuelocal() { this.$emit('search', this.valuelocal); } }
}
</script>
```

**Comment by v1talii-dev** [comment]
Есть какие-либо обновления по данной задаче? @Hatead1 может создадите merge request?

**Comment by v1talii-dev** [comment]
Переопределил компонент Search и теперь работает корректно. Конечно, желательно это зафиксить в компоненте библиотеки.
```javascript
import ContextMenuPlugin, { Menu } from 'rete-context-menu-plugin';
// ...
editor.use(ContextMenuPlugin, {
 vueComponent: {
   extends: { ...Menu },
   components: {
     Search: {
       name: 'Search',
       template: `<div class="search"><input v-model="valuelocal"/></div>`,
       props: ['value', 'search'],
       data() {
         return { valuelocal: this.value };
       },
       watch: {
        valuelocal() {
          this.$emit('search', this.valuelocal);
        }
      }
    }
  }
});
```

**Comment by Hatead1** [comment]
Виталий, я пас. Мне проще для своих нужд подправить исходник плагина и не думать, нужно это автору или нет.

**Comment by v1talii-dev** [comment]
@Hatead1 понял вас. В любом случае, спасибо, что предложили решение.
