### ISSUE TITLE
Should be free from Vue specific stuff?

### ISSUE THREAD

**Issue by trsh** [retejs/context-menu-plugin#3]
And use whatever renderers stuff it can. Otherwise every new Renderer will require new Context menu. :/

**Comment by trsh** [comment]
No idea how this could be organized :/

**Comment by Ni55aN** [comment]
Vue.js is used to simplify and speed up development. It does not depend on any render plugin or your project's framework

**Comment by trsh** [comment]
What about such structure?:

1) Vue independent/core stuff in root
2) Vue stuff in renderers/vue

And Some way to switch renderers when building. This way we can add/support new ones for context menu.

**Comment by Ni55aN** [comment]
For what? I prefer to develop on Vue.js, and I have no reason to switch to other renderers. Moreover, it does not interfere with the use this in projects on React or Angular

**Comment by trsh** [comment]
> Moreover, it does not interfere with the use this in projects on React or Angular

@Ni55aN ok. Not directly, just that it's a full stack framework, over another one. ~80 uncompressed KB for the device to process.

Nerveless for that I developed the stage0 alternatives.
