### ISSUE TITLE
Scrolling in the context menu

### ISSUE THREAD

**Issue by verloka** [retejs/context-menu-plugin#31]
Scrolling in the context menu does not work. The sub-menu is long, so I made the height equal to 350 pixels, and scrolling doesn't work in the menu, it works in the area.
![presentation](https://user-images.githubusercontent.com/5623092/76321314-887d3e00-62ea-11ea-8e51-8a84087e7124.gif)

**Comment by Ni55aN** [comment]
https://github.com/retejs/context-menu-plugin/issues/23

**Comment by verloka** [comment]
> #23

so, do i need a new vue component?

**Comment by verloka** [comment]
scrolling not working, scroll bar exists

**Comment by Ni55aN** [comment]
I added `stopPtopagation()` for `wheel` event in `v0.6.0-rc.1`. This fixes the issue with scrolling, but changes the behavior when scrolling is not active - area will not be zoomed when context menu has no scroll, also a parent element with scrolling will scroll.
