### ISSUE TITLE
Add Subitems to Context Menue

### ISSUE THREAD

**Issue by Ibrahimvse** [retejs/context-menu-plugin#38]
Hi , I am using Angular-render-plugin . I have 7 Components (Archi,sdsm,hdsm,bugspace,rootcover,download file,graph) I want items to show in the contextmenue as follow:
Archi>Archi
Titan> [Sdsm,Hdsm,Bugspace,Rootcover]
Utilities> [Download file,Graph]

I tried to add them to items but it dosent work can you please show me how that can be done?

**Comment by Hatead1** [comment]
1. Add to all nodes constructor    
        this.data.path = n; // n - unique number for group, 1 - Archi, 2 - sdsm, hdsm... 
2. Add to ContextMenuPlugin init
editor.use(ContextMenuPlugin.default, {
  allocate(component) {
    if (component.data.path === 1) return ['Archi']; 
    if (component.data.path === 2) return ['Titan']; 
    if (component.data.path === 3) return ['Utilities']; 
  }
}
