### ISSUE TITLE
Disable timeout delay closing the menu

### ISSUE THREAD

**Issue by yoshivda** [retejs/context-menu-plugin#39]
Is there a way to disable the timeout delay closing the whole context menu? With the delay on, submenus in the context menu will overlap when switching from one to the other. I would like to put the delay to 0 here, but that renders the menu absolutely unusable: as soon as the mouse moves, the full context menu is closed. Obviously this is not what I wanted either. Is it possible to only disable the delay for the submenus and simply keep the context menu open until the user clicks somewhere else, not make it close on mouse move/leave?

**Comment by kazanture** [comment]
@yoshivda i had the same problem and switched to previous version.
