### ISSUE TITLE
[FR] more configurable menu

### ISSUE THREAD

**Issue by trsh** [retejs/context-menu-plugin#4]
1) For auto add, when `allocate` returns null or false, exclude it from context menu
2) Some param to add by hand formed context menu: 

```
{
  xx: {
    yy: TComponent,
    zz: function() {
      doSomething();
    } 
  }
}
```

if wish so!

**Comment by Ni55aN** [comment]
[v0.3.0](https://www.npmjs.com/package/rete-context-menu-plugin)

1. Exactly what you need
2. Only functions allowed

**Comment by trsh** [comment]
@Ni55aN cool. I'll try to adjust my work, so it more less identical.

As for two.. then  to add node we have to do something like:

```
items: {
        'Click me'(){ 
           var n1 = await components[0].createNode({num: 2});
           n1.position = [mousepos.x, mousepos.y];
        }
    }
```

in run code?

**Comment by Ni55aN** [comment]
I think `['Click me']` in `allocate` is more preferable

**Comment by trsh** [comment]
@Ni55aN only if you don't care to hand-craft your context menu :)))

**Comment by Ni55aN** [comment]
@trsh `items` and `allocate` can be used simultaneously

**Comment by trsh** [comment]
@Ni55aN can't imagine how that could work O_O

!!??

Would be nice if you push a more advanced example or read-me. For now it's very unclear, how to hand craft a menu (only components I want in my order with my names), with adding components.

**Comment by Ni55aN** [comment]
```js
editor.use(ContextMenuPlugin, { 
    allocate(c) {
        return ['Components']
    },
    items: {
        'Functions': {
           test(){ console.log('Works!') }
        },
       'Components': {
           'Fake component'(){ console.log(':)))')}
       }
    }
});
```
