### ISSUE TITLE
Context menu does not stay open on MacOS / Safari

### ISSUE THREAD

**Issue by jdonzallaz** [retejs/context-menu-plugin#44]
Hi,
On MacOS / Safari, the context menu does not work correctly. It opens on Control+mousedown, but disappears immediately on mouseup (when we release the click). It can be reproduced on the example page: https://rete.js.org/#/examples/basic. It works well on Firefox.

Tested with MacOS 10.15.6 and Safari 14.0.

**Comment by jdonzallaz** [comment]
It's still a problem for us.

**Comment by Ni55aN** [comment]
Are you planning to migrate to v2?
