### ISSUE TITLE
Settings "delay" don't working.  

### ISSUE THREAD

**Issue by ovyavor** [retejs/context-menu-plugin#70]
Hi. "Delay" does't work correctly in last stable version. I need to close context menu by click not only area of editor. It was a good idea to close by delay. How can I fixed it?

**Comment by Ni55aN** [comment]
How to reproduce it? 
If I specify this option in https://codepen.io/Ni55aN/pen/xzgQYq, it works correctly

**Comment by ovyavor** [comment]
You used the old version of plugin:
https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.6.0/build/context-menu-plugin.min.js
This example with 1.0.0.alpha9
https://codesandbox.io/s/nifty-breeze-97vjku?file=/src/index.js

**Comment by Ni55aN** [comment]
this version isn't stable and was developed for Vue 3 compatibility. I would recommend using v2 (where the issue of compatibility is solved in other way), or I could accept the PR with the fix

**Comment by ovyavor** [comment]
Ok, thanks. I'll take v2.
