### ISSUE TITLE
vue-render-plugin compatibility

### ISSUE THREAD

**Issue by daef** [retejs/context-menu-plugin#71]
I've read on https://retejs.org/docs/guides/context-menu#render-context-menu that this plugin doesn't support vue rendering yet. What would have to be done to support vue? I'd really like to use it :)

**Comment by Ni55aN** [comment]
do you want to customize it with Vue components?

For now I have other tasks in priority, but I plan to add the appropriate presets to Vue and Angular, but I can’t say exactly when this will happen

**Comment by daef** [comment]
No, I dont want to customize it, I just want to use the context menu to add nodes to my dataflow :)

**Comment by Ni55aN** [comment]
so you can easily do it using the React render plugin along with your main render plugin :)

Check it out:
```bash
rete-kit app --next -s vue -v 3 -f "Vue render,Context menu"
```
This command creates a Vue.js project with the Vue render plugin and a context menu that will use the React render plugin.
The only disadvantage of this approach is the slightly larger bundle size.

**Comment by daef** [comment]
What is this magic :) The last time I wanted to read up on rete-kit I think I only found a 'under construction' placeholder.

Thanks!

**Comment by Ni55aN** [comment]
you gave me an idea for a tweet 😁

![image](https://user-images.githubusercontent.com/8259641/232829384-e87527a4-d35f-446c-9102-3bd6a6ea8269.png)

**Comment by daef** [comment]
When I click the link to the docs on twitter I see the content flashing once before it gets replaced with `Docs section not found` thou :/

**Comment by daef** [comment]
![image](https://github.com/retejs/context-menu-plugin/assets/2098598/db962dc9-b153-4885-9026-30c2ac4903af)

**Comment by Ni55aN** [comment]
@daef you probably visited the site a few weeks ago and the browser cached outdated PWA data with this issue. You can either wait for the browser to download the new version of the site (it does this silently in the background), or force clear the cache in the DevTools -> Application -> Storage -> Clear site data

**Comment by daef** [comment]
This sounds like a really broken design - especially for docs, which are potentially visited semiregulary... Can't this fail more gracefully? I thought this PWA stuff was supposed to make things better.

**Comment by Ni55aN** [comment]
this is powered by @vite-pwa/nuxt. So far I have not delved into its config, maybe there is something to improve this. Or I'll just disable it

**Comment by daef** [comment]
I managed to read the contents by mashing Esc before the js kicks in :)
