### ISSUE TITLE
Default behavior supressed when using context menu plugin, even if it is disabled

### ISSUE THREAD

**Issue by dbriscoe511** [retejs/context-menu-plugin#72]
I would like to have the browser default spellcheck accessible when the user clicks on a item that allows spellcheck (IE a `textarea`).

I wrote some code to accomplish this:
```
export function hasSpellCheck(event) {
    const target = event.target;
    if (!target.spellcheck) {
        return false;
    } else {
        return true;
    }
}
```
And the code to disable the context menu
```
editor.on('showcontextmenu', ({e,node}) => {
    if (hasSpellCheck(e)) {
      console.log("has misspelled word, skipping context");
      return false;
    }
    return !e.node || !editor.components.get(e.node.name).data.noContextMenu;
  });
```
I confirmed that this disables the context menu correctly. however, if this menu is disabled, the browser default behavior (showing a menu that includes spellcheck) does not show up. I would think if this menu is disabled, the default behavior would come back, but I may just be missing something.

**Comment by Ni55aN** [comment]
Indeed, `showcontextmenu` has nothing to do with preventing the default context menu. If you need to "prioritize" your textarea's context menu, you can add "stopPropagation" to its contextmenu event.

**Comment by dbriscoe511** [comment]
Oh yep, you are totally right. Thanks for your help

**Comment by Ni55aN** [comment]
@dbriscoe511 you have not accepted your invitation yet 🙂
