### ISSUE TITLE
v2 context menu

### ISSUE THREAD

**Issue by cbureriu** [retejs/context-menu-plugin#77]
need to style the v2 context menu without CSS overrides if possible
the default blue theme doesn't work for my application

**Comment by Ni55aN** [comment]
what's your stack?

In React you can substitute components, but for other integrations this option is not available.

Instead, if overriding styles doesn't work for you, you can copy the context menu preset and make changes to it (e.g. for Vue.js https://github.com/retejs/vue-plugin/tree/main/src/presets/context-menu). This approach has the same disadvantages as making a fork, but it is a small part
