### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by davidgraeff** [retejs/context-menu-plugin#8]
You could use `npm i lodash.debounce` instead of the full lodash.

**Comment by Ni55aN** [comment]
`lodash.debounce` doesn't have UMD or IIFE module. Therefore, I can not use a dependency in the codepen


https://www.jsdelivr.com/package/npm/lodash.debounce

**Comment by davidgraeff** [comment]
Ok. Thanks for investigating
