### ISSUE TITLE
Clicking on item with subitems causes type error

### ISSUE THREAD

**Issue by Claybarn** [retejs/context-menu-plugin#81]
Clicking on a menu item that has subitems (where the desired behavior is to have no action) causes the error:

 props.data.handler is not a function

This error can be reproduced by clicking on the "extra" menu item found at the example [here](https://retejs.org/examples/context-menu). 

I imagine the solution is to add a empty function like:
`handler() {}`

on [this](https://github.com/retejs/context-menu-plugin/blob/35831a081dfa64c4539406c8e93b12194eb66698/src/presets/classic/factory.ts#L32) line. I [forked](https://github.com/Claybarn/context-menu-plugin) this repo in the hopes of making a PR with this change, however I can't ensure it fixes the problem because the rete-cli emits a "Type generating failed" error when attempting to compile the context-menu-plugin.

**Comment by Ni55aN** [comment]
thanks, I'll take a look

duplicates https://github.com/retejs/context-menu-plugin/issues/79
