### ISSUE TITLE
Visuell bug with submenus

### ISSUE THREAD

**Issue by Plaximo** [retejs/context-menu-plugin#85]
Hello,

I just experienced a visuell bug with the submenus. When switching menus the collapsing and expanding is updating with a delay.

Video attached:
https://github.com/retejs/context-menu-plugin/assets/7767387/3e9d2e38-5fef-4d61-b35e-3e6cc730022f

Thanks and kind regards

**Comment by Ni55aN** [comment]
this is due to large delay. It can be changed

```ts
new ContextMenuPlugin({ delay: 100 })
```

Basically, it doesn't work smoothly because the submenu timers are independent, but it can be improved sometime
